name: Check File Changes

on:
  push:
    branches:
      - bugfix-2.1.x

jobs:
  check-files:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "GITHUB_EVENT_BEFORE=${{ github.event.before }}" >> $GITHUB_ENV
          echo "GITHUB_EVENT_AFTER=${{ github.event.after }}" >> $GITHUB_ENV

      - name: Run Python script
        run: |
          python3 .github/workflows/check_file_changes.py
